module.exports = [
"A big fish in a small pond",
"A bird in the hand is worth two in the bush",
"A bunch of fives",
"A chain is only as strong as its weakest link",
"A countenance more in sorrow than in anger",
"A Daniel come to judgement",
"A diamond in the rough",
"A diamond is forever",
"A different kettle of fish",
"A dish fit for the gods",
"A dog is a man's best friend",
"A drop in the bucket",
"A drop in the ocean",
"A fate worse than death",
"A feather in one's cap",
"A fish out of water",
"A fish rots from the head down",
"A fly in the ointment",
"A fool and his money are soon parted",
"A fool's paradise",
"A foot in the door",
"A foregone conclusion",
"A friend in need is a friend indeed",
"A golden key can open any door",
"A good man is hard to find",
"A house divided against itself cannot stand",
"A knight in shining armour",
"A legend in one's own lifetime",
"A leopard cannot change its spots",
"A little bird told me",
"A little knowledge is a dangerous thing",
"A little of what you fancy does you good",
"A load of cobblers",
"A load of codswallop",
"A man after my own heart",
"A man who is his own lawyer has a fool for a client",
"A millstone around one's neck",
"A ministering angel shall my sister be",
"A miss is as good as a mile",
"A nation of shopkeepers",
"A nest of vipers",
"A no-brainer",
"A nod is as good as a wink",
"A norange",
"A penny for your thoughts",
"A picture is worth a thousand words",
"A piece of the action",
"A pig in a poke",
"A place for everything and everything in its place",
"A plague on both your houses",
"A priori",
"A red rag to a bull",
"A riddle wrapped up in an enigma",
"A rolling stone gathers no moss",
"A rose by any other name would smell as sweet",
"A rose is a rose is a rose",
"A safe pair of hands",
"A sea change",
"A shot in the arm",
"A sight for sore eyes",
"A skeleton in the closet",
"A sledgehammer to crack a nut",
"A sorry sight",
"A stitch in time saves nine",
"A stone's throw",
"A thing of beauty is a joy forever",
"A tinker's damn",
"A turn up for the books",
"A watched pot never boils",
"A wolf in sheep's clothing",
"A woman needs a man like a fish needs a bicycle",
"A woman's place is in the home",
"A word in edgeways",
"Abandon all hope ye who enter here",
"Abide with me",
"About face",
"About turn",
"Above board",
"Abracadabra",
"Absence makes the heart grow fonder",
"Absent without leave",
"Absolute power corrupts absolutely",
"Accidentally on purpose",
"Accidents will happen",
"According to Hoyle",
"Ace in the hole",
"Achilles' heel",
"Acid test",
"Acronyms",
"Across the board",
"Act of God",
"Act the giddy goat",
"Action man",
"Adam's ale",
"Aga saga",
"Against the grain",
"Age before beauty",
"Age cannot wither her, nor custom stale her infinite variety",
"Agree to disagree",
"Aid and abet",
"Air kiss",
"Air quotes",
"Al fresco",
"Alas, poor Yorick! I knew him, Horatio",
"Alike as two peas in a pod",
"Alive and kicking",
"All agog",
"All at sea",
"All fingers and thumbs",
"All Greek to me",
"All in all",
"All intents and purposes",
"All of a sudden",
"All present and correct",
"All publicity is good publicity",
"All singing, all dancing",
"All systems go",
"All that glitters is not gold",
"All things come to he who waits",
"All things must pass",
"All you can eat",
"Alter ego",
"Amber nectar",
"An albatross around one's neck",
"An apple a day keeps the doctor away",
"An arm and a leg",
"An axe to grind",
"An Englishman's home is his castle",
"An eye for an eye, a tooth for a tooth",
"An ill wind",
"An offer he can't refuse",
"An Oxford scholar",
"Anchors aweigh",
"Angry young man",
"Ankle biter",
"Annus horribilis",
"Another think coming",
"Apple pie order",
"April fool",
"Arms akimbo",
"Ars longa, vita brevis",
"As alike as two peas in a pod",
"As bald as a coot",
"As black as Newgate's knocker",
"As brown as a berry",
"As busy as a bee",
"As cold as any stone",
"As cool as a cucumber",
"As cute as a bug's ear",
"As daft as a brush",
"As dead as a dodo",
"As dead as a doornail",
"As different as chalk and cheese",
"As easy as pie",
"As fast as greased lightning",
"As fine as frog's hair",
"As fit as a butcher's dog",
"As fit as a fiddle",
"As good as gold",
"As good luck would have it",
"As happy as a clam",
"As happy as a sandboy",
"As happy as Larry",
"As happy as...",
"As high as a kite",
"As keen as mustard",
"As mad as a hatter",
"As mad as a March hare",
"As nice as ninepence",
"As old as Methuselah",
"As old as the hills",
"As pleased as Punch",
"As pure as the driven snow",
"As queer as a nine bob note",
"As safe as houses",
"As snug as a bug in a rug",
"As straight as a die",
"As the crow flies",
"As thick as thieves",
"As white as snow",
"As X as Y",
"Asap - As soon as possible",
"Ashes to ashes dust to dust",
"Ask a silly question and you'll get a silly answer",
"At loggerheads",
"At one fell swoop",
"At one's beck and call",
"At one's wit's end",
"At sixes and sevens",
"Augur well",
"Auld lang syne",
"Away with the fairies",
"Baby blues",
"Baby boomer",
"Baby father",
"Back the field",
"Back to basics",
"Back to square one",
"Back to the drawing board",
"Back-seat driver",
"Backroom boy",
"Backward in coming forward",
"Bad books",
"Bad egg",
"Bad hair day",
"Badger to death",
"Bag and baggage",
"Baker's dozen",
"Bald as a coot",
"Bale out/bail out",
"Ball and chain",
"Bandy words",
"Bane of your life",
"Bang on about",
"Baptism of fire",
"Barking mad",
"Barking up the wrong tree",
"Barrel of laughs",
"Basket case",
"Bated breath",
"Bats in the belfry",
"Batten down the hatches",
"Battle royal",
"Be afraid, be very afraid",
"Be enthralled",
"Be still, my beating heart",
"Bean counter",
"Beast with two backs",
"Beat a hasty retreat",
"Beat around the bush",
"Beat swords into ploughshares",
"Beat the living daylights out of someone",
"Beauty is in the eye of the beholder",
"Beauty is only skin deep",
"Beck and call",
"Bed of roses",
"Bee in your bonnet",
"Beef and reef",
"Beelzebub has a devil for a sideboard",
"Been there, done that",
"Beer and skittles",
"Beetle-browed",
"Before you can say Jack Robinson",
"Beg the question",
"Beggar belief",
"Beggars can't be choosers",
"Behind every great man there's a great woman",
"Behind the eight ball",
"Bell the cat",
"Bell, book and candle",
"Belle of the ball",
"Bells and whistles",
"Below the belt",
"Below the salt",
"Belt and braces",
"Belt up",
"Best bib and tucker",
"Bet your bottom dollar",
"Better half",
"Better late than never",
"Better to have loved and lost than never to have loved at all",
"Between a rock and a hard place",
"Between the Devil and the deep blue sea",
"Between two stools",
"Between you, me and the bed-post",
"Beware of Greeks bearing gifts",
"Beware the Ides of March",
"Beyond belief",
"Beyond our ken",
"Beyond the pale",
"Biblical phrases",
"Big wig",
"Bill Stickers is innocent",
"Billy no mates",
"Billy-o - Like",
"Binge drinking",
"Bird in the hand is worth two in the bush - A",
"Birds and the bees - The",
"Birds of a feather flock together",
"Bite the bullet",
"Bite the dust",
"Bitter end - The",
"Black as Newgate's knocker",
"Black sheep of the family",
"Black-on-black",
"Blast from the past - A",
"Blaze a trail",
"Blind leading the blind - The",
"Blind-man's buff",
"Bling-bling",
"Blonde bombshell",
"Blood and thunder",
"Blood is thicker than water",
"Blood toil tears and sweat",
"Blood, sweat and tears",
"Bloody-minded",
"Blot on the landscape",
"Blow a raspberry - see raspberry tart",
"Blow your mind",
"Blow your own trumpet",
"Blown to smithereens",
"Blue blood",
"Blue moon (Once in a)",
"Blue-plate special",
"Bob's your uncle",
"Bode well",
"Bodice ripper",
"Body - phrases related to the human body",
"Body surfing",
"Bog standard",
"Bolt from the blue",
"Bone dry",
"Bone idle",
"Bone up on",
"Booby prize",
"Booby trap",
"Boogie-woogie",
"Booze cruise",
"Born again",
"Born with a silver spoon in one's mouth",
"Born within the sound of Bow Bells",
"Boss eyed",
"Bottle out",
"Bottom drawer",
"Bottom-up",
"Bought the farm",
"Bowled a maiden over",
"Box and Cox",
"Box-seat - in the",
"Boxing Day",
"Brand spanking new",
"Brass monkey weather",
"Brass tacks - get down to",
"Bread always falls buttered side down",
"Bread of life - The",
"Break a leg",
"Break the ice",
"Bricks and clicks",
"Bring home the bacon",
"Bring home the bacon",
"Broad in the beam",
"Broke - if it ain't, don't fix it",
"Bronx cheer",
"Brook no truck with",
"Brown as a berry",
"Browned off",
"Brownie points",
"Brummagem screwdriver",
"Brush - As daft as a",
"Bubble and squeak",
"Buck stops here - The",
"Bucket list",
"Buckle down",
"Bugger Bognor!",
"Buggins' turn",
"Bullet - Bit the, Bite the",
"Bums on seats",
"Bun in the oven",
"Bunch of fives - A",
"Bunny boiler",
"Burn the candle at both ends",
"Burning the midnight oil",
"Bury the hatchet",
"Bury your head in the sand",
"Busy as a bee",
"Butt end of the stick - The",
"Butter no parsnips - Fine words",
"Butter side down",
"Butter wouldn't melt in his mouth",
"Butterfingers",
"By and large",
"By dint of",
"By gum",
"By hook or by crook",
"By the board",
"By the book",
"By the short hairs",
"By the skin of your teeth",
"By your leave",
"Bygones be bygones - Let",
"Caesar Salad",
"Call a spade a spade",
"Call of the wild - The",
"Camera cannot lie - The",
"Can't be overestimated/can't be underestimated",
"Can't hold a candle to",
"Canteen culture",
"Canterbury pace",
"Carbon footprint",
"Carbon-copy",
"Card-sharp",
"Carey Street - On",
"Carpe diem",
"Carry coals to Newcastle",
"Cart before the horse - Put the",
"Carte blanche",
"Cash on the nail",
"Cast the first stone",
"Cat got your tongue?",
"Cat may look at a king - A",
"Cat out of the bag - Let the",
"Cat's Cradle",
"Catbird seat - In the",
"Catch 22",
"Caught by the short hairs",
"Caught in a cleft stick",
"Caught red-handed",
"Chain is only as strong as its weakest link - A",
"Chaise lounge",
"Chalk and cheese",
"Champ at the bit",
"Chance would be a fine thing",
"Channel surfing",
"Charity begins at home",
"Charley horse",
"Charm offensive",
"Charmed life",
"Cheap at half the price",
"Cheek by jowl",
"Cherchez la femme",
"Chew the cud",
"Chick flick",
"Chickens come home to roost",
"Children should be seen and not heard",
"Chinese whispers",
"Chinless wonder",
"Chip off the old block",
"Chip on your shoulder",
"Chit-chat",
"Chock-a-block",
"Chop and change",
"Chop-chop",
"Chow down",
"Christmas box - A",
"Christmas card verses",
"Clean breast - make a",
"Clear blue water",
"Cleft stick - In a",
"Cliff-hanger",
"Climb on the bandwagon",
"Cloak and dagger",
"Clod-hopper",
"Clog up",
"Close quarters",
"Close your eyes and think of England",
"Close, but no cigar",
"Cloud cuckoo land",
"Cloud nine",
"Club sandwich",
"Clue - don't have a",
"Clutch at straws",
"Coals to Newcastle - Carry",
"Cobblers - A load of",
"Cock a snook",
"Cock and bull story",
"Cock-a-hoop",
"Cock-sure",
"Cock-up",
"Cockney rhyming slang",
"Codswallop - a load of",
"Cogito ergo sum",
"Coin a phrase",
"Cold as any stone",
"Cold comfort",
"Cold enough to freeze the balls off a brass monkey",
"Cold feet",
"Cold shoulder",
"Cold turkey",
"Collywobbles - The",
"Colour up",
"Come a cropper",
"Come clean",
"Come on down",
"Come up trumps",
"Come what come may",
"Comes to the crunch - (When it)",
"Common sense",
"Comparisons are odious",
"Compassion fatigue",
"Complete shambles",
"Cook the books",
"Cookie cutter",
"Cool as a cucumber",
"Cool Britannia",
"Cop an attitude",
"Copper-bottomed",
"Cor blimey",
"Cordon bleu",
"Cost an arm and a leg",
"Cotton on to",
"Cotton-picking",
"Countenance more in sorrow than in anger - A",
"Counting sheep",
"Country bumpkin",
"Course of true love never did run smooth - The",
"Crack of doom - The",
"Crackpot",
"Crapper - The",
"Crocodile tears",
"Crop up",
"Crown jewels",
"Cry havoc and let slip the dogs of war",
"Curate's egg",
"Curiosity killed the cat",
"Curry favour",
"Customer is always right - The",
"Cut and run",
"Cut of your jib - The",
"Cut off without a penny",
"Cut off your nose to spite your face",
"Cut the mustard",
"Cut to the chase",
"Cute as a bug's ear",
"Daft as a brush",
"Damp squib",
"Dance attendance on",
"Daniel come to judgement",
"Darby and Joan",
"Dark horse",
"Dark side - The",
"Darkest hour - The",
"Darkest hour is just before the dawn - The",
"Darling buds of May",
"Dash to pieces",
"Date rape",
"Davy Jones' locker",
"Daylight robbery",
"Dead as a dodo",
"Dead as a doornail",
"Dead cat bounce",
"Dead ringer",
"Delusions of grandeur",
"Derring-do",
"Designer stubble",
"Deus ex machina",
"Devil and the deep blue sea",
"Devil Incarnate - The",
"Devil take the hindmost - The",
"Devil to pay - The",
"Devil's advocate",
"Diamond in the rough",
"Diamond is forever - A",
"Dicky-bird - Not a",
"Die has been cast - The",
"Die-hard",
"Different kettle of fish",
"Differently abled",
"Dirt bag",
"Dish fit for the gods - A",
"Do unto others as you would have them do to you",
"Dock your pay",
"Doesn't know shit from Shinola",
"Doff your hat",
"Dog days",
"Dog in the manger",
"Dog is a man's best friend",
"Dog's bollocks",
"Dog's breakfast",
"Dog's dinner",
"Doldrums - in the",
"Dollars to doughnuts",
"Don't call us, we'll call you",
"Don't change horses in midstream",
"Don't count your chickens before they are hatched",
"Don't die like I did",
"Don't go there",
"Don't have a clue",
"Don't keep a dog and bark yourself",
"Don't know shit from Shinola",
"Don't let the bastards grind you down",
"Don't look a gift horse in the mouth",
"Don't shut the stable door after the horse has bolted",
"Don't throw the baby out with the bathwater",
"Don't try to teach your Grandma to suck eggs",
"Done a runner",
"Done to a turn",
"Donkey's years",
"Doom and gloom",
"Double cross",
"Double Dutch",
"Double entendre",
"Double whammy",
"Down at heel",
"Down in the dumps",
"Down the pan",
"Down the tubes",
"Down to the wire",
"Drag race",
"Dragged through a hedge backwards",
"Draw a blank",
"Draw your horns in",
"Dreams of empire",
"Dressed to the nines",
"Drink like a fish",
"Driving while black",
"Drop in the bucket - A",
"Drop-dead gorgeous",
"Dropping like flies",
"Drummed out of the army",
"Ducks and drakes",
"Dumb blonde",
"Dust up",
"Dutch - My old",
"Dutch courage",
"Duvet day",
"Ear candy",
"Ear-mark",
"Early bird catches the worm - The",
"Early to bed and early to rise makes a man healthy, wealthy and wise",
"Easy as pie",
"Eat drink and be merry",
"Eat humble pie",
"Eat my hat",
"Eaten out of house and home",
"Economical with the truth",
"Eeny, meeny, miny, mo",
"Egg on",
"Eighty six",
"Elbow-grease",
"Elementary my dear Watson",
"Elephant in the room",
"Elvis has left the building",
"Emperor's new clothes",
"End of story",
"Ends of the earth - The",
"Englishman's home is his castle",
"Enough is as good as a feast",
"Enough is enough",
"Eponymous Phrases",
"Et tu, Brute",
"Ethnic cleansing",
"Euphemisms",
"Even at the turning of the tide",
"Every cloud has a silver lining",
"Everybody out",
"Exceedingly well read",
"Exception that proves the rule - The",
"Excuse me while I kiss this guy",
"Excuse my French",
"Extraordinary rendition",
"Eye candy - see ear candy",
"Eye of newt and toe of frog, wool of bat and tongue of dog",
"Face that launched a thousand ships - The",
"Face the music",
"Faff about",
"Fag end",
"Failing to plan is planning to fail",
"Faint-hearted",
"Fair and square",
"Fair dinkum",
"Fair exchange is no robbery",
"Fair play",
"Fair to middling",
"Fairy-tale ending",
"Fait accompli",
"Faith will move mountains",
"Fall from grace",
"Fall guy",
"Fall off the back of a lorry",
"Fall on your sword",
"Famous for fifteen minutes",
"Famous last words (dying statements of famous people - a list)",
"Famous last words (the ironic phrase)",
"Fancy free",
"Fancy pants",
"Fanny Adams - Sweet",
"Far be it from me",
"Far from the madding crowd",
"Farmers",
"Fashion victim",
"Fast and loose",
"Fast asleep",
"Fate worse than death - A",
"Fathom out",
"Feather in one's cap - A",
"Fed up",
"Feeding frenzy",
"Fell swoop - At one",
"Fellow traveller",
"Female of the species is more deadly then the male - The",
"Fend off",
"Fiddlesticks",
"Fiddling while Rome burns",
"Fie, foh, fum, I smell the blood of an Englishman",
"Field day",
"Fifteen minutes of fame",
"Fifth column",
"Fifth estate",
"Fight fire with fire",
"Fight the good fight",
"Filthy rich",
"Finagle's Law",
"Fine as frog's hair",
"Fine words butter no parsnips",
"Finger lickin good",
"Fingers and thumbs",
"First water",
"First World",
"Fish or cut bait",
"Fish out of water - A",
"Fish rot from the head down",
"Fit as a fiddle",
"Fits and starts",
"Fits to a tee",
"Five o'clock shadow",
"Fixer-upper",
"Flash in the pan",
"Flat out",
"Flavor of the month",
"Flesh and blood",
"Flogging a dead horse",
"Floozie in the jacuzzi - The",
"Flotsam and jetsam",
"Fly by the seat of one's pants",
"Fly in the ointment",
"Fly off the handle",
"Fly on the wall",
"Foam at the mouth",
"Fobbed off",
"Folk Etymology - The Nonsense Nine",
"Fool and his money are soon parted - A",
"Fool's errand",
"Fool's gold",
"Fool's paradise - A",
"Fools rush in where angels fear to tread",
"Foot in the door - A",
"Foot of our stairs - The",
"For all intents and purposes",
"For crying out loud",
"For ever and a day",
"For every thing there is a season",
"For good measure",
"For keeps",
"For the birds",
"For whom the bell tolls",
"Forbidden fruit",
"Foregone conclusion",
"Forewarned is forearmed",
"Forgive them for they know not what they do",
"Forlorn hope",
"Foul play",
"Four by two",
"Four corners of the earth",
"Frailty, thy name is woman",
"Freeze the balls off a brass monkey - cold enough to",
"Freezing temperatures",
"French phrases",
"Friday afternoon car",
"Friend in need is a friend indeed - A",
"Friends, Romans, Countrymen, lend me your ears",
"Frog in the throat - A",
"Frog's hair- as fine as",
"From pillar to post",
"From sea to shining sea",
"From strength to strength",
"Fruits of your loins",
"Fuddy-duddy",
"Full Monty - The",
"Full of piss and vinegar",
"Full tilt",
"Full to the gunwales",
"Funny farm",
"Fuzzy wuzzy",
"Gad zooks (or gadzooks)",
"Game is afoot - The",
"Game is up - The",
"Game of two halves",
"Gee whiz",
"Generation X",
"Genius is one percent inspiration and 99 percent perspiration",
"Get - underway",
"Get a word in edgeways",
"Get down to brass tacks",
"Get medieval",
"Get off on the wrong foot",
"Get off your high horse",
"Get on my wick",
"Get one's dander up",
"Get over it",
"Get the pip",
"Get the sack",
"Get the upper hand",
"Get thee behind me Satan",
"Get underway",
"Get used to it",
"Get your dander up",
"Get your goat",
"Giddy aunt",
"Giddy goat",
"Gild the lily",
"Gilt off the gingerbread",
"Ginger up",
"Ginger",
"Ginned up",
"Give a man a fish and you will feed him for a day",
"Give a wide berth",
"Give no quarter",
"Give the Devil his due",
"Give up the ghost",
"Glass ceiling",
"Gloom and doom",
"Go and boil your head",
"Go berserk",
"Go by the board",
"Go by the book",
"Go Dolally",
"Go for a burton",
"Go haywire",
"Go like the clappers",
"Go off half-cocked",
"Go out on a limb",
"Go over like a lead balloon",
"Go postal",
"Go pound sand",
"Go the whole hog",
"Go to pot",
"Go to the dogs",
"Go to the foot of our stairs",
"Go to the mattresses",
"Go whole hog",
"Go-faster",
"God is dead",
"God rot them",
"Godfrey Daniel",
"Going for a burton",
"Going to hell in a handbasket",
"Golden key can open any door - A",
"GOLF - Gentlemen only, ladies forbidden",
"Gone for a burton",
"Good as gold",
"Good in parts",
"Good man is hard to find - A",
"Good measure - For",
"Good men and true",
"Good riddance",
"Good Samaritan",
"Goody two-shoes",
"Goody, goody gumdrops",
"Gordon Bennett",
"Got my mojo working",
"Grace of God - There but for ...",
"Grand slam",
"Grandfather clock",
"Granny dumping",
"Grasp the nettle",
"Grass up",
"Graveyard shift",
"Greased lightning",
"Great balls of fire",
"Great minds think alike",
"Great unwashed - the",
"Green eyed monster",
"Gregory Peck",
"Gridlock",
"Grind to a halt",
"Grinning like a Cheshire cat",
"Grist to the mill",
"Gry - Words ending in",
"Guinea pig",
"Gung ho",
"Gussied-up",
"Guts for garters",
"Hair of the dog that bit you",
"Hairy eyeball",
"Halcyon days",
"Half a loaf is better than no bread",
"Half inch",
"Half-cocked",
"Half-hearted",
"Hand over fist",
"Handbags at ten paces",
"Handle with kid gloves",
"Hands down",
"Hanged, drawn and quartered",
"Hanky-panky",
"Happy as a clam",
"Happy as a sandboy",
"Happy as Larry",
"Happy clappy",
"Happy slapping",
"Harbinger of doom",
"Hard and fast",
"Hard cases make bad law",
"Hard cheese",
"Hard hearted",
"Hard lines",
"Hard man is good to find - A",
"Hark, hark! the lark at heaven's gate sings",
"Harp on",
"Harvest moon",
"Has the cat got your tongue?",
"Hasta la vista, baby",
"Haste makes waste",
"Hat trick",
"Have a Captain Cook",
"Have a dekko",
"Have an axe to grind",
"Have an inkling",
"Have no truck with",
"Have your guts for garters",
"Haven't got a clue",
"He who can, does; he who cannot, teaches",
"He who laughs last laughs longest",
"He will give the Devil his due",
"Head over heels",
"Heads up",
"Hear hear",
"Heard it through the grapevine",
"Heart's content",
"Heavens to Betsy",
"Heavens to Murgatroyd",
"Heavy metal",
"Hedge your bets",
"Heebie-jeebies - The",
"Hell has no fury like a woman scorned",
"Hell in a handbasket",
"Hell or high water",
"Helter-skelter",
"Here lies one whose name is writ in water",
"Het up",
"Hiding to nothing - On a",
"Higgledy-piggledy",
"High and dry",
"High and mighty",
"High as a kite",
"High five",
"High horse - get off your",
"High on the hog",
"High time",
"High, wide and handsome",
"High-flyer",
"Hissy fit",
"History is bunk",
"Hit the ground running",
"Hit the hay",
"Hit the nail on the head",
"Hither and yon",
"Hobby-horse",
"Hobson's choice",
"Hocus pocus",
"Hoi polloi",
"Hoist with your own petard",
"Hoity-toity",
"Hold your horses",
"Homonyms",
"Honesty is the best policy",
"Hooray Henry",
"Horse and cart",
"Horse feathers",
"Horse's mouth - straight from the",
"Horse, a horse, my kingdom for a horse - A",
"Horse-sense",
"Hot off the press",
"Hot on the heels",
"Hot-blooded",
"House divided against itself cannot stand - A",
"Household words",
"Houston, we have a problem",
"How are the mighty fallen?",
"How do you do?",
"How now brown cow?",
"How sharper than a serpent's tooth it is to have a thankless child",
"Hugger-mugger",
"Hung, drawn and quartered",
"Hunky-dory",
"Hunt and peck",
"Hush puppies",
"I bear a charmed life",
"I have not slept one wink",
"I have nothing to declare but my genius",
"I have nothing to offer but blood toil tears and sweat",
"I haven't got a clue",
"I see you stand like greyhounds in the slips",
"I spy with my little eye",
"I told you is was ill",
"I will swing for you",
"I will wear my heart upon my sleeve",
"I'll be there with bells on",
"I'll go to the foot of our stairs",
"I'll have your guts for garters",
"I'm stumped",
"Identity theft",
"If I had my druthers",
"If it ain't broke, don't fix it",
"If music be the food of love, play on",
"If the cap fits",
"If the mountain will not come to Muhammad, then Muhammad must go to the mountain",
"If the shoe fits",
"If wishes were horses, beggars would ride",
"If you can't stand the heat, get out of the kitchen",
"If you think that, you have another think coming",
"Ill wind",
"Imitation is the sincerest form of flattery",
"In a cleft stick",
"In a nutshell",
"In a pickle",
"In a pig's eye",
"In a quandary",
"In a trice",
"In an interesting condition",
"In for a penny, in for a pound",
"In like Flynn",
"In limbo",
"In my minds eye",
"In someone's bad books",
"In spades",
"In stitches",
"In the bag",
"In the box-seat",
"In the buff",
"In the cart",
"In the catbird seat",
"In the club",
"In the doghouse",
"In the doldrums",
"In the limelight",
"In the nick of time",
"In the pink",
"In the red",
"In the same boat",
"In your face",
"Indian giver",
"Indian summer",
"Infra dig",
"Innocent until proven guilty",
"Inside out",
"Iron hoof",
"Is the Pope Catholic?",
"Is the Pope Polish?",
"Is this a dagger which I see before me?",
"It ain't over till the fat lady sings",
"It came like a bolt from the blue",
"It is meat and drink to me",
"It never rains but it pours",
"It's all Greek to me",
"It's all grist to the mill",
"It's better to give than to receive",
"It's better to light a candle than curse the darkness",
"It's not rocket science",
"It's that man again",
"Ivory tower",
"Jack - phrases that include the name Jack",
"Jack in the box",
"Jack of all trades, master of none",
"Jack Palancing",
"Jack Robinson - Before you can say",
"Jack the lad",
"Jam tomorrow",
"Jerry built",
"Jet-black",
"Jimmy Horner",
"Jimmy Riddle",
"Jobs for the boys",
"Johnny on the spot",
"Join the colours",
"Joined at the hip",
"Jot or tittle",
"Jump on the bandwagon",
"Jump the gun",
"Jump the shark",
"Jury is still out",
"Just deserts",
"Just in time",
"Kangaroo court",
"Katy bar the door",
"Keen as mustard",
"Keep a stiff upper lip",
"Keep a wide berth",
"Keep at bay",
"Keep body and soul together",
"Keep it under your hat",
"Keep schtum",
"Keep the ball rolling",
"Keep up with the Joneses",
"Keep your chin up",
"Keep your distance",
"Keep your hands clean",
"Keep your nose clean",
"Keep your nose to the grindstone",
"Keep your pecker up",
"Keep your powder dry",
"Keepy-uppy",
"Kettle of fish",
"Khyber pass",
"Kick the bucket",
"Kick your heels",
"Kickin' - Alive and",
"Kilroy was here",
"King James' Version of the Bible",
"Kiss and tell",
"Kiss me Hardy",
"Kith and kin",
"Knee-jerk reaction",
"Knick-knack",
"Knight in shining armour",
"Knock back",
"Knock into a cocked hat",
"Knock off",
"Knock on wood",
"Know the ropes",
"Know which side your bread is buttered",
"Know which way the wind blows",
"Know your onions",
"Knuckle down",
"Knuckle under",
"Kowtow to",
"La dolce vita",
"La-di-da",
"La-la land",
"Labour of love",
"Lackadaisical",
"Ladies' room",
"Lager frenzy",
"Laid out in lavender",
"Lamb to the slaughter",
"Lame duck",
"Land of nod - The",
"Lardy-dardy",
"Lark about",
"Last but not least",
"Last straw - The",
"Latin Phrases",
"Laugh like a drain",
"Laughing-stock",
"Laurels - rest on one's",
"Lay it on with a trowel",
"Lead balloon - Go over like a",
"Lead-pipe cinch",
"Learn the ropes",
"Left hand doesn't know what the right hand is doing",
"Left in the lurch",
"Legend in one's own lifetime",
"Leopard cannot change its spots - A",
"Less is more",
"Let a thousand flowers bloom",
"Let bygones be bygones",
"Let not poor Nelly starve",
"Let not the sun go down on your wrath",
"Let or hindrance",
"Let sleeping dogs lie",
"Let the cat out of the bag",
"Let them eat cake",
"Let there be light",
"Let your hair down",
"Let's roll",
"Level playing field",
"Lick and a promise",
"Lick into shape",
"Lickety-split",
"Lie low",
"Lies, damned lies and statistics",
"Life begins at forty",
"Life in the 1500s - folk etymologies",
"Life of Riley",
"Life's not all beer and skittles",
"Life's too short",
"Like a chicken with its head cut off",
"Like a moth to a flame",
"Like being savaged by a dead sheep",
"Like billy-o",
"Like it or lump it",
"Like the clappers",
"Like the Dickens",
"Like two peas in a pod",
"Lily-livered",
"Lions led by donkeys",
"Little bird told me - A",
"Little knowledge is a dangerous thing - A",
"Little of what you fancy does you good - A",
"Little pitchers have big ears",
"Live long and prosper",
"Living daylights",
"Living off the fat of the land",
"Living on borrowed time",
"Lo and behold",
"Load of cobblers",
"Load of codswallop",
"Loaf of bread",
"Local derby",
"Lock stock and barrel",
"Long in the tooth",
"Look before you leap",
"Loose cannon",
"Loose lips sink ships",
"Lose face",
"Lose your marbles",
"Love is blind",
"Love that dare not speak its name - The",
"Loved-up",
"Lunatic fringe",
"Mad as a hatter",
"Mad as a March hare",
"Magical realism",
"Main chance",
"Make a bee-line for",
"Make a clean breast of it",
"Make a pig's ear of",
"Make a virtue of necessity",
"Make haste",
"Make hay while the sun shines",
"Make him an offer he can't refuse",
"Make my day",
"Make no bones about",
"Make your hair stand on end",
"Mal de mer",
"Man after my own heart - A",
"Man does not live by bread alone",
"Man who is his own lawyer has a fool for a client - A",
"Man's inhumanity to man",
"Many a little makes a mickle",
"Many a true word is spoken in jest",
"Many are called but few are chosen",
"Many happy returns",
"Mare's nest",
"Marital aid",
"Market forces",
"Marry in haste, repent at leisure",
"May you live in interesting times",
"McCoy - The real",
"Mea culpa",
"Meat and drink",
"Meat and two veg.",
"Meet your Waterloo",
"Men in suits",
"Men's evil manners live in brass; their virtues we write in water",
"Mend fences",
"Merry Christmas",
"Method in my madness",
"Mexican wave",
"Mickey Finn",
"Middle for diddle",
"Middle of the road",
"Might and main",
"Mighty oaks from little acorns grow",
"Milk of human kindness",
"Minced oaths",
"Minced words",
"Mind your Ps and Qs",
"Mind's ear",
"Mind's eye",
"Ministering angel shall my sister be - A",
"Mint condition",
"Misery acquaints a man with strange bedfellows",
"Misquotes",
"Miss is as good as a mile",
"Moaning Minnie",
"Mondegreens",
"Money for old rope",
"Monstrous regiment of women",
"Montezuma's Revenge",
"Monty - The full",
"Moot point",
"Morbid obesity",
"More bang for your buck",
"More fool you",
"More haste, less speed",
"More honoured in the breach than in the observance",
"More light!",
"Morning person",
"Mother country",
"Motley crew",
"Mouth-watering",
"Movable feast",
"Movers and shakers",
"Moving finger writes - The",
"Moving the goalposts",
"Much Ado about Nothing",
"Much of a muchness",
"Mud - your name is",
"Mull (something) over",
"Multitude of sins",
"Mum's the word",
"Mumbo jumbo",
"Murphy's Law",
"Music has charms to soothe the savage breast",
"Mutt and Jeff",
"Mutt's nuts - The",
"Mutton dressed as lamb",
"My bad",
"My better half",
"My cup of tea",
"My cup runneth over",
"My giddy aunt",
"My husband and I",
"My mind's eye",
"My old china",
"My old Dutch",
"My salad days",
"My stars and garters",
"Ménage à trois",
"Nail your colours to the mast",
"Namby-pamby",
"Name and shame",
"Name is mud",
"Nasty, brutish and short",
"Nation of shopkeepers - A",
"Nautical phrases",
"Ne'er cast a clout till May be out",
"Ne'er do well",
"Near the knuckle",
"Necessity is the mother of invention",
"Needs must",
"Neither a borrower nor a lender be",
"Neither fish nor flesh, nor good red herring",
"Neither here nor there",
"Nest of vipers - A",
"Nest-egg",
"Never give a sucker an even break",
"Never knowingly undersold",
"Never look a gift horse in the mouth",
"Never the twain shall meet",
"Never-never land",
"New kid on the block",
"Nice as ninepence",
"Nice kettle of fish",
"Night owl",
"Nine days' wonder",
"Nip and tuck",
"Nip in the bud",
"Nitty-gritty",
"No dice",
"No holds barred",
"No laughing matter",
"No man is an island",
"No more cakes and ale?",
"No names: no pack-drill",
"No quarter given",
"No rest for the wicked",
"No room to swing a cat",
"No truck with",
"No way, Jose",
"No-brainer",
"Nod - The land of",
"Nod is as good as a wink - A",
"Norange - A",
"Nosy parker",
"Not a dicky-bird",
"Not by a long chalk",
"Not for all the tea in China",
"Not my cup of tea",
"Not playing with a full deck",
"Not rocket science",
"Not tonight Josephine",
"Not worth a plugged nickel",
"Not worth the candle",
"Nothing is certain but death and taxes",
"Nothing succeeds like success",
"Nothing ventured, nothing gained",
"Now is the winter of our discontent",
"Nth degree",
"Nul points",
"Nutshell - In a",
"O Romeo, Romeo! wherefore art thou Romeo?",
"O ye, of little faith",
"Odds bodkins",
"Off his own bat",
"Off the record",
"Off with his head",
"Offing - In the",
"Oh, my stars and garters",
"Oh, they have slain the Earl of Moray and Lady Mondegreen",
"Okay",
"Okey-dokey",
"Old as Methuselah",
"Old as the hills",
"Old chestnut",
"Old codger",
"Old hat",
"Old lang syne - see auld lang syne",
"On a hiding to nothing",
"On a wing and a prayer",
"On Carey Street",
"On cloud nine",
"On queer street",
"On tenterhooks",
"On the ball",
"On the bubble",
"On the button",
"On the dole",
"On the fiddle",
"On the pig's back",
"On the QT",
"On the shoulders of giants",
"On the side of the angels",
"On the wagon",
"On the warpath",
"On with the motley",
"On your beam ends",
"On your tod",
"Once in a blue moon",
"Once more unto the breach, dear friends, once more",
"One fell swoop - At",
"One foot in the grave",
"One for the road",
"One good turn deserves another",
"One over the eight",
"One sandwich short of a picnic",
"One small step for man",
"One stop shop",
"One swallow doesn't make a summer",
"One's heart's content",
"One-hit wonder",
"Oops-a-daisy",
"Open season",
"Ough - the many ways to pronounce",
"Out of sight",
"Out of sight, out of mind",
"Out of sorts",
"Out of the jaws of death",
"Out of the mouths of babes and sucklings",
"Out on a limb",
"Over a barrel",
"Over the moon",
"Over the top",
"Overpaid, oversexed, and over here",
"Oxo cube",
"P.D.Q. - pretty damn quick",
"Packed to the gunwales",
"Paddle your own canoe",
"Paint the town red",
"Panic stations",
"Paper tiger",
"Parting shot / Parthian shot",
"Pass over to the other side",
"Pass the buck",
"Paying guest - A",
"Pearls before swine",
"Pears for your heirs",
"Peeping Tom",
"Peg out",
"Pell-mell",
"Pennies from heaven",
"Penny dreadful",
"Penny for your thoughts - A",
"Penny pinching",
"Penny saved is a penny earned - A",
"Penny wise and pound foolish",
"Pester power",
"Peter out",
"Petty cash",
"Phrases that people get wrong",
"Physician heal thyself",
"Pick 'n' mix",
"Picture is worth a thousand words - A",
"Picture-perfect",
"Pie - as easy as",
"Pie in the sky",
"Piece of cake - A",
"Piece of piss",
"Piece of the action",
"Pig and whistle",
"Pig in a poke",
"Pig's back - on the",
"Pig's ear",
"Pigeon-chested",
"Piggyback",
"Pigs might fly",
"Pin money",
"Pip - Get the/got the /have the",
"Pipe down",
"Pipe dream - A",
"Piping hot",
"Piss and vinegar - Full of",
"Pitch black",
"Pitch dark",
"Place for everything and everything in its place - A",
"Plague on both your houses - A",
"Plain sailing",
"Plates of meat",
"Play by ear",
"Play Devil's advocate",
"Play ducks and drakes",
"Play fast and loose",
"Play it again Sam",
"Play second fiddle",
"Play silly buggers",
"Play the giddy goat",
"Play the race card",
"Pleased as Punch",
"Plug-ugly",
"Plugged nickel",
"Poetic justice",
"Point Percy at the porcelain",
"Point to point",
"Point-and-click",
"Point-blank",
"Politically correct",
"Pommy bashing",
"Pomp and circumstance",
"Pond life",
"Pony and trap",
"Pony up",
"Pop goes the weasel",
"Popular fallacies - The Nonsense Nine",
"Pork pies",
"POSH - Port out, starboard home",
"Pot calling the kettle black - The",
"Pound of flesh",
"Pour oil on troubled waters",
"Power corrupts; absolute power corrupts absolutely",
"Power dressing",
"Powers that be - The",
"Praying at the porcelain altar",
"Preaching to the choir",
"Preposterous",
"Press into service",
"Pretty kettle of fish",
"Pretty penny - A",
"Prick up your ears",
"Prime time",
"Primrose path",
"Procrastination is the thief of time",
"Proof of the pudding is in the eating - The",
"Proverbs - A list of",
"Ps and Qs - Mind your",
"Pull in your horns",
"Pull out all the stops",
"Pull the other one, it's got bells on",
"Pull the wool over your eyes",
"Pull up stakes",
"Pull your finger out",
"Pull your horns in",
"Pull yourself up by your bootstraps",
"Pulling one's leg",
"Punch above one's weight",
"Pure as the driven snow",
"Purple patch",
"Push the boat out",
"Push the envelope",
"Put a damper on",
"Put a sock in it",
"Put a spanner in the works",
"Put on the wooden overcoat",
"Put on your thinking cap",
"Put paid to",
"Put the cart before the horse",
"Put the mockers on",
"Put the wood in the hole",
"Put up your dukes",
"Put your back up",
"Put your best foot forward",
"Put your nose out of joint",
"Pyrric victory",
"Quality time",
"Quarter - Give no",
"Queer as a nine bob note",
"Queer Street",
"Queer the pitch",
"Quick and the dead - The",
"Quicker than lager turns to piss",
"Quid pro quo",
"Quotations",
"Rabbit and pork",
"Rack and ruin",
"Rack your brains",
"Rag, tag and bobtail",
"Rag-and-bone man",
"Raining cats and dogs",
"Raining stair-rods",
"Raise Cain",
"Rank and file",
"Raspberry tart",
"Rat arsed",
"Raze to the ground",
"Read between the lines",
"Read the riot act",
"Real McCoy",
"Red herring",
"Red in tooth and claw",
"Red rag to a bull - A",
"Red sky at night ...",
"Red tape",
"Red-handed (caught)",
"Red-letter day",
"Reduplicated phrases",
"Religion is the opium of the people",
"Rest on his laurels",
"Revenge is a dish best served cold",
"Rhyme nor reason",
"Rhyming slang",
"Richard of York gave battle in vain",
"Richard the Third",
"Riddle wrapped up in an enigma - A",
"Riding shotgun",
"Riff-raff",
"Riley - the life of",
"Ring a ring o'roses, a pocketful of posies, atishoo, atishoo, all fall down",
"Ring down the curtain",
"Ring the changes",
"Ring-fencing",
"Rinky-dink",
"Rise and shine",
"Road apples",
"Road less travelled - The",
"Road rage",
"Roasted to a turn",
"Rob Peter to pay Paul",
"Rock and roll",
"Romeo, Romeo, wherefore art thou Romeo?",
"Rose by any other name would smell as sweet - A",
"Rose is a rose is a rose",
"Rosie Lea",
"Rough diamond",
"Round Robin",
"Route one",
"Rub of the green",
"Rule of thumb",
"Rum do",
"Rumpy-pumpy",
"Run a mile",
"Run amok",
"Run of the mill",
"Run out of steam",
"Run rings around",
"Run the gauntlet",
"Sacred cow",
"Safe as houses - As",
"Safe pair of hands - A",
"Safe sex",
"Salad days",
"Salt of the earth - The",
"San fairy Ann",
"Sandwich short of a picnic",
"Save face",
"Save one's bacon",
"Saved by the bell",
"Savoir faire",
"Say cheese",
"Say goodnight Gracie",
"Scapegoat",
"Scarper",
"Scot-free",
"Scott (Sir Walter - phrases coined by)",
"Screw your courage to the sticking place",
"Sea change",
"Sealed with a loving kiss",
"Season of mists and mellow fruitfulness",
"Second-guess",
"Security blanket",
"See a pin and pick it up, all the day you'll have good luck; see a pin and let it lie, bad luck you'll have all day",
"See red",
"Seen better days",
"Send packing",
"Senior citizen",
"Sent to Coventry",
"Separate the sheep from the goats",
"Set one's cap at",
"Set your teeth on edge",
"Seven-year itch",
"Sex and shopping",
"Sexton Blake",
"Shaggy dog story",
"Shake a leg",
"Shakers and movers",
"Shakespeare (phrases and sayings of)",
"Shall I compare thee to a summer's day?",
"Shambles",
"Shanks' mare/shanks' pony",
"Share and share alike",
"Shebang - The whole",
"Shilly-shally",
"Ship shape and Bristol fashion",
"Shit end of the stick - The",
"Shit for brains",
"Shiver my timbers",
"Shoddy",
"Shoot through",
"Short end of the stick - The",
"Short shrift",
"Shot across the bows",
"Shot heard 'round the world - The",
"Shot in the arm",
"Shot in the dark",
"Show a leg - see shake a leg",
"Show your mettle",
"Shrinking violet",
"Shuffle off this mortal coil",
"Shut your cake-hole",
"Siamese twins",
"Sick puppy (A)",
"Sight for sore eyes (A)",
"Silence is golden",
"Silly Billy",
"Silly season",
"Silver bullet",
"Silver lining - every cloud has a",
"Similes",
"Sir Walter Scott (phrases coined by)",
"Sitting pretty",
"Sixes and sevens - At",
"Skeleton in the closet",
"Skid row",
"Skin and blister",
"Sledgehammer to crack a nut - A",
"Sleep like a top",
"Sleep on a clothesline",
"Sleep tight",
"Sleeveless errand",
"Sloane Ranger",
"Slush fund",
"Smallest room in the house - The",
"Smart casual",
"Smoke and mirrors",
"Snug as a bug in a rug",
"So sue me",
"Soap-dodger",
"Sod's Law",
"Sold down the river",
"Some are born great, some achieve greatness, and some have greatness thrust upon 'em",
"Some men are born mediocre, some men achieve mediocrity, and some men, have mediocrity thrust upon them",
"Someone is walking over my grave",
"Something for the weekend sir?",
"Something nasty in the woodshed",
"Something old, something new, something borrowed, something blue",
"Son of a bitch",
"Son of a gun",
"Sorry sight",
"Sound bite",
"Sound out",
"Sour grapes",
"Space, the final frontier",
"Spare the rod and spoil the child",
"Speak of the Devil",
"Speak softly and carry a big stick",
"Special relationship",
"Spelling-bee",
"Spend a penny",
"Spick and span",
"Spill the beans",
"Spin doctor",
"Spitting feathers",
"Spitting image",
"Spoonerisms",
"Spring forward, fall back",
"Spruce-up",
"Square meal",
"Squeaky bum time",
"Stand and deliver",
"Stand up guy",
"Standing on the shoulders of giants",
"Star-crossed lovers",
"Stark, raving mad",
"Stars and garters - My",
"Start from scratch",
"Steal a march",
"Steal my thunder",
"Stick in the mud",
"Sticks and stones may break my bones",
"Sticky wicket",
"Stiff upper lip",
"Stiffen the sinews",
"Stinking rich",
"Stitch in time saves nine - A",
"Stone the crows",
"Stone's throw",
"Stony-hearted",
"Stool pigeon",
"Storm in a teacup",
"Straight as a die",
"Straight from the horse's mouth",
"Strain at the leash",
"Strait and narrow",
"Strait-laced",
"Stranger danger",
"Stranger than fiction - Truth is",
"Strike while the iron is hot",
"Stuff and nonsense",
"Stump up",
"Such is life",
"Surf and turf",
"Surfing the Net/surfing the Internet/surfing the Web",
"Survival of the fittest",
"Suspension of disbelief",
"Swan song",
"Sweet Fanny Adams",
"Swing for you",
"Swing the lead",
"Tail wagging the dog - The",
"Take a back seat",
"Take care of the pence and the pounds will take care of themselves",
"Take down a peg or two",
"Take potluck",
"Take the bit between your teeth",
"Take the cake",
"Take the gilt off the gingerbread",
"Take the Mickey",
"Take the upper hand",
"Take umbrage",
"Take with a grain of salt",
"Taken aback",
"Talk of the Devil",
"Talk the talk",
"Talk through one's hat",
"Talk to the hand",
"Tall story",
"Tanstaafl - (there's no such thing as a free lunch)",
"Tattoo phrases and sayings",
"Tawdry",
"Tea leaf",
"Technicolor yawn",
"Tell it to the marines",
"Tempest in a teapot",
"Test your mettle - see show your mettle",
"That's all folks!",
"That's all she wrote",
"That's one small step for a man, a giant leap for mankind",
"The - unkindest cut of all",
"The ants are my friends, they're blowing in the wind",
"The Apple of my eye",
"The apple of my eye",
"The back of beyond",
"The balance of power",
"The balance of power",
"The balance of trade",
"The balance of trade",
"The bane of my life",
"The bee's knees",
"The bee's knees",
"The belle of the ball",
"The best laid schemes of mice and men",
"The Big Apple",
"The Big Easy",
"The birds and the bees",
"The bitter end",
"The blind leading the blind",
"The bread of life",
"The buck stops here",
"The call of the wild",
"The camera cannot lie",
"The chickens come home to roost",
"The collywobbles",
"The course of true love never did run smooth",
"The crack of doom",
"The Crapper",
"The customer is always right",
"The cut of your jib",
"The dark side",
"The darkest hour is just before the dawn",
"The Devil Incarnate",
"The Devil is in the details",
"The Devil makes work for idle hands to do",
"The Devil take the hindmost",
"The Devil to pay",
"The die has been cast",
"The early bird catches the worm",
"The elephant in the room",
"The emperor's new clothes",
"The ends of the earth",
"The exception which proves the rule",
"The face that launched a thousand ships",
"The fat of the land",
"The female of the species is more deadly then the male",
"The fifth estate",
"The floozie in the jacuzzi",
"The fly in the ointment",
"The full monty",
"The game is afoot",
"The game is up",
"The great - unwashed",
"The great unwashed",
"The hair of the dog that bit you",
"The hairy eyeball",
"The heebie-jeebies",
"The jury is still out",
"The land of nod",
"The last straw",
"The law is an ass",
"The life of Riley",
"The living daylights",
"The love that dare not speak its name",
"The monstrous regiment of women",
"The more the merrier",
"The moving finger writes",
"The mutt's nuts",
"The nth degree",
"The opera ain't over till the fat lady sings",
"The pen is mightier than the sword",
"The pip - Get/got/have",
"The pot calling the kettle black",
"The powers that be",
"The proof of the pudding is in the eating",
"The quick and the dead",
"The real McCoy",
"The road less travelled",
"The road to hell is paved with good intentions",
"The salt of the earth",
"The seven-year itch",
"The shoemaker always wears the worst shoes",
"The short end of the stick",
"The shot heard 'round the world",
"The sky's the limit",
"The smallest room in the house",
"The straw that broke the camel's back",
"The tail wagging the dog",
"The third degree",
"The toast of the town",
"The triumph of hope over experience",
"The upper hand",
"The usual suspects",
"The whole kit and caboodle",
"The whole nine yards",
"The whole shebang",
"The word fast, and phrases that derive from it.",
"The writing is on the wall",
"The wrong side of the blanket",
"The year dot",
"The Yellow Peril",
"There are three kinds of lies...",
"There but for the grace of God, go I",
"There is more than one way to kill a cat",
"There is no alternative",
"There's an R in the month",
"There's method in my madness",
"There's no fool like an old fool",
"There's no such thing as a free lunch (Tanstaafl)",
"There's no such thing as bad publicity",
"There's one (a sucker) born every minute",
"They couldn't hit an elephant at this distance",
"Thick and thin",
"Thick as two short planks",
"Thin air - Vanish into",
"Thing of beauty is a joy forever - A",
"Things that go bump in the night",
"Think outside the box",
"Thinking cap",
"Third degree - The",
"Third time lucky",
"Thomas Paine - The writings of",
"Thorn in the flesh",
"Thou shalt not kill",
"Though this be madness, yet there is method in it",
"Three score and ten",
"Three sheets to the wind",
"Three strikes and you are out",
"Through thick and thin",
"Throw in the towel",
"Throw your hat into the ring",
"Thumbs up",
"Thus far into the bowels of the land",
"Ticked off",
"Tickle the ivories",
"Tickled pink",
"Tide over",
"Tie the knot",
"Till the cows come home",
"Tilting at windmills",
"Time and tide wait for no man",
"Tinker's damn",
"Tissue of lies",
"Tit for tat",
"Titfer",
"Tits up",
"To a T",
"To all intents and purposes",
"To be or not to be, that is the question",
"To beggar belief",
"To big for your boots",
"To boldly go where no man has gone before",
"To boot",
"To cast the first stone",
"To err is human; to forgive divine",
"To gild refined gold, to paint the lily",
"To sleep: perchance to dream: ay, there's the rub",
"To the manner born",
"To the nth degree",
"To travel hopefully is a better thing than to arrive",
"Toast of the town",
"Toe the line",
"Toe-curling",
"Toffee-nosed",
"Tommy Atkins",
"Tomorrow is another day",
"Tongue in cheek",
"Too big for your breeches",
"Too much of a good thing",
"Toodle-oo",
"Tooth and nail",
"Top dog",
"Top drawer",
"Top notch",
"Topsy-turvy",
"Total shambles",
"Touch and go",
"Touch with a barge-pole - Wouldn't",
"Touch wood",
"Touchy-feely",
"Tout de suite",
"Tower of strength",
"Train surfing",
"Trick or treat",
"Trip the light fantastic",
"Trouble and strife",
"True blue",
"Truth is stranger than fiction",
"Truth will out",
"Tuckered out",
"Turn a blind eye",
"Turn of phrase",
"Turn the tables",
"Turn up for the books",
"Turn up trumps",
"Twelve good men and true",
"Twenty four seven",
"Twenty three skidoo",
"Two cents worth",
"Two heads are better than one",
"Two peas in a pod",
"Under the auspices of",
"Under the thumb",
"Under your hat - Keep it",
"Uneasy lies the head that wears a crown",
"Union Jack",
"Up a blind alley",
"Up a gum tree",
"Up in arms",
"Up shit creek without a paddle",
"Up the ante",
"Up the apples and pears",
"Up the duff",
"Up the pole",
"Up the wooden hill to Bedfordshire",
"Up to snuff",
"Upper crust",
"Upper hand",
"Ups-a-daisy",
"Upset the apple-cart",
"Upside down",
"Urban myth",
"Use your loaf",
"Using a sledgehammer to crack a nut",
"Usual suspects - The",
"Valentine's Day Poems and Sayings",
"Van surfing",
"Vanish into thin air",
"Veg out",
"Verbosity leads to unclear, inarticulate things",
"Vice versa",
"Vicious circle",
"Vis-a-vis",
"Visit the ladies' room",
"Vorsprung Durch Technik",
"Walk free",
"Walk the plank",
"Walk the walk",
"Walter Scott (phrases coined by)",
"Warts and all",
"Watch the birdie",
"Watching brief",
"Wave a red rag to a bull",
"Wax lyrical",
"Wax poetic",
"We are a grandmother",
"We are not amused",
"We few, we happy few, we band of brothers",
"We have seen better days",
"We know where you live",
"Weakest link - A chain is only as strong as its",
"Wear the trousers",
"Wear your heart on your sleeve",
"Weasel words",
"Wee-wee",
"Well heeled",
"Well read",
"Wet behind the ears",
"Wet blanket",
"What a piece of work is man",
"What are you like?",
"What football is all about",
"What God has joined together let no man put asunder",
"What part of no don't you understand?",
"What you see is what you get - wysiwyg",
"What's in a name? That which we call a rose by any other name would smell as sweet",
"What's not to like?",
"What's up Doc?",
"When in Rome, do as the Romans do",
"When it comes to the crunch",
"When pigs fly",
"When the shit hits the fan",
"Where there's muck there's brass",
"Whet your appetite",
"Which is which?",
"Which witch is which?",
"While you live, tell truth and shame the Devil!",
"Whip round",
"Whipper snapper",
"Whipping boy",
"Whistle and flute",
"Whistle blower",
"Whistle down the wind",
"White as snow",
"White bread",
"White elephant",
"Whole kit and caboodle - The",
"Whole nine yards - The",
"Whole shebang - The",
"Whole-hearted",
"Whoops-a-daisy",
"Why does bread always fall butter side down?",
"Wick - you get on my",
"Wide berth - Keep a",
"Wild and woolly",
"Wild goose chase",
"Willy nilly",
"Win hands down",
"Win one for the Gipper",
"Wing it",
"Winter drawers on",
"Wish you were here",
"With bells on",
"Without let or hindrance",
"Without so much as a by your leave",
"Woe betide you",
"Woe is me",
"Wolf in sheep's clothing",
"Woman needs a man like a fish needs a bicycle - A",
"Woman's place is in the home - A",
"Women and children first",
"Wooden hill to Bedfordshire",
"Word association football",
"Word for word",
"Word in edgeways - A",
"Word in your shell-like - A",
"Words ending in gry",
"Worse for wear",
"Worth one's salt",
"Wotcher",
"Wouldn't touch with a barge-pole",
"Wreak havoc",
"Writing is on the wall - The",
"Wrong end of the stick - The",
"Wrong side of the blanket - The",
"Yada yada",
"Year dot - The",
"Yellow Peril",
"Yellow-belly",
"You are what you eat",
"You can lead a horse to water but you can't make it drink",
"You can lead a whore to culture but you can't make her think",
"You can't get blood out of a stone",
"You can't have your cake and eat it too",
"You can't teach an old dog new tricks",
"You get on my wick",
"You look as if you've been dragged through a hedge backwards",
"You'll wonder where the yellow went when you brush your teeth with Pepsodent",
"You've never had it so good",
"Young turk",
"Your money or your life",
"Your name is mud",
"Zero tolerance",
"Zig-zag",
"À la carte",
"À la mode"
]